name: Push Changes to GitHub

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to GitHub
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/TheShiboman/five28hertz-website.git main --force
